---
title: "babynames"
author: "Evelyn Cai"
date: "1/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(babynames)
library(dplyr)
library(tidyverse)
library(ggplot2)
```



```{r babynames}
babynames %>%
  filter(name %in% c("Evelyn", "Ruth", "Michelle")) %>%
  group_by(sex) %>%
  ggplot(mapping = aes(x = year, y = n, fill = name)) +
           geom_col() + facet_wrap(~sex)
  
```

```{r babynames_top1000}
top100 <- babynames %>%
  filter(year == max(year)) %>%
  arrange(desc(n)) %>%
  head(100)
```

``` {r join}
new100 <- babynames %>%
  inner_join(top100, "name")
```

``` {r plot}
top1000 <- babynames %>%
  filter(year==max(year)) %>% 
  arrange(desc(n)) %>%
  slice(1:1000)

x1000 <- babynames %>%
  inner_join(top1000, "name")
  
  
```

notes: 
summary(year) tells you more about max and min
slice(1:1000) does the same thing as head(1000)

Questions about the dataset
- if names shift from being commonly male to female or vice versa
- whether most popular names have been fads/classics thru looking at their densities per year
- length of popular names
- nicknames spawning off of a long name and becoming more popular